# Generated by Django 5.1.1 on 2024-11-21 09:15

import django.db.models.deletion
import utxo_indexer.models.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PruneSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_indexed_tail_height', models.PositiveIntegerField()),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_state', models.CharField(choices=[('created', 'Created'), ('sync', 'Syncing'), ('up_to_date', 'Up to date'), ('error', 'Error')], max_length=10)),
                ('latest_tip_height', models.PositiveIntegerField()),
                ('latest_indexed_height', models.PositiveIntegerField()),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UtxoBlock',
            fields=[
                ('block_hash', utxo_indexer.models.model_utils.HexString32ByteField(max_length=64, primary_key=True, serialize=False)),
                ('block_number', models.PositiveIntegerField()),
                ('timestamp', models.PositiveBigIntegerField()),
                ('previous_block_hash', utxo_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ('transactions', models.PositiveIntegerField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='utxo_indexe_block_n_7be93d_idx'), models.Index(fields=['timestamp'], name='utxo_indexe_timesta_7390df_idx'), models.Index(fields=['previous_block_hash'], name='utxo_indexe_previou_58894c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UtxoTransaction',
            fields=[
                ('transaction_id', utxo_indexer.models.model_utils.HexString32ByteField(max_length=64, primary_key=True, serialize=False)),
                ('block_number', models.PositiveIntegerField()),
                ('timestamp', models.PositiveBigIntegerField()),
                ('payment_reference', utxo_indexer.models.model_utils.HexString32ByteField(max_length=64, null=True)),
                ('source_addresses_root', utxo_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ('is_native_payment', models.BooleanField(default=False)),
                ('transaction_type', models.CharField()),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='utxo_indexe_block_n_2a386e_idx'), models.Index(fields=['timestamp'], name='utxo_indexe_timesta_4e0245_idx'), models.Index(fields=['payment_reference'], name='utxo_indexe_payment_b900d6_idx'), models.Index(fields=['transaction_type'], name='utxo_indexe_transac_0b109b_idx'), models.Index(fields=['source_addresses_root'], name='utxo_indexe_source__3782c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionInputCoinbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_n', models.PositiveIntegerField()),
                ('vin_coinbase', models.CharField()),
                ('vin_sequence', models.PositiveBigIntegerField()),
                ('transaction_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utxo_indexer.utxotransaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField()),
                ('value', models.CharField()),
                ('script_key_asm', models.CharField()),
                ('script_key_hex', models.CharField()),
                ('script_key_req_sigs', models.CharField(blank=True, null=True)),
                ('script_key_type', models.CharField()),
                ('script_key_address', models.CharField(max_length=128)),
                ('transaction_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utxo_indexer.utxotransaction')),
            ],
            options={
                'unique_together': {('transaction_link', 'n')},
            },
        ),
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField()),
                ('value', models.CharField()),
                ('script_key_asm', models.CharField()),
                ('script_key_hex', models.CharField()),
                ('script_key_req_sigs', models.CharField(blank=True, null=True)),
                ('script_key_type', models.CharField()),
                ('script_key_address', models.CharField(max_length=128)),
                ('vin_n', models.PositiveIntegerField()),
                ('vin_previous_txid', utxo_indexer.models.model_utils.HexString32ByteField(max_length=64)),
                ('vin_vout_index', models.PositiveIntegerField()),
                ('vin_sequence', models.PositiveBigIntegerField()),
                ('vin_script_sig_asm', models.CharField()),
                ('vin_script_sig_hex', models.CharField()),
                ('transaction_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utxo_indexer.utxotransaction')),
            ],
            options={
                'unique_together': {('transaction_link', 'vin_n')},
            },
        ),
    ]
