# Generated by Django 5.1.1 on 2024-11-15 20:45

import django.db.models.deletion
import utxo_indexer.models.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PruneSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_indexed_tail_height', models.PositiveIntegerField(db_column='latestIndexedTailHeight')),
                ('timestamp', models.PositiveIntegerField(db_column='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='TipSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_state', models.CharField(choices=[('created', 'Created'), ('sync', 'Syncing'), ('up_to_date', 'Up to date'), ('error', 'Error')], db_column='syncState', max_length=10)),
                ('latest_tip_height', models.PositiveIntegerField(db_column='latestTipHeight')),
                ('latest_indexed_height', models.PositiveIntegerField(db_column='latestIndexedHeight')),
                ('timestamp', models.PositiveIntegerField(db_column='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='UtxoBlock',
            fields=[
                ('block_hash', utxo_indexer.models.model_utils.HexString32ByteField(db_column='blockHash', max_length=64, primary_key=True, serialize=False)),
                ('block_number', models.PositiveIntegerField(db_column='blockNumber')),
                ('timestamp', models.PositiveBigIntegerField(db_column='timestamp')),
                ('previous_block_hash', utxo_indexer.models.model_utils.HexString32ByteField(db_column='previousBlockHash', max_length=64)),
                ('transactions', models.PositiveIntegerField(db_column='transactions')),
                ('confirmed', models.BooleanField(db_column='confirmed', default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='utxo_indexe_blockNu_4ad566_idx'), models.Index(fields=['timestamp'], name='utxo_indexe_timesta_7390df_idx'), models.Index(fields=['previous_block_hash'], name='utxo_indexe_previou_b19022_idx')],
            },
        ),
        migrations.CreateModel(
            name='UtxoTransaction',
            fields=[
                ('transaction_id', utxo_indexer.models.model_utils.HexString32ByteField(db_column='transactionId', max_length=64, primary_key=True, serialize=False)),
                ('block_number', models.PositiveIntegerField(db_column='blockNumber')),
                ('timestamp', models.PositiveBigIntegerField(db_column='timestamp')),
                ('payment_reference', utxo_indexer.models.model_utils.HexString32ByteField(db_column='paymentReference', max_length=64)),
                ('source_addresses_root', utxo_indexer.models.model_utils.HexString32ByteField(db_column='sourceAddressesRoot', max_length=64)),
                ('is_native_payment', models.BooleanField(db_column='isNativePayment', default=False)),
                ('transaction_type', models.CharField(db_column='transactionType')),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='utxo_indexe_blockNu_331255_idx'), models.Index(fields=['timestamp'], name='utxo_indexe_timesta_4e0245_idx'), models.Index(fields=['payment_reference'], name='utxo_indexe_payment_c4185f_idx'), models.Index(fields=['transaction_type'], name='utxo_indexe_transac_b5a07e_idx'), models.Index(fields=['source_addresses_root'], name='utxo_indexe_sourceA_e49349_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionInputCoinbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_n', models.PositiveIntegerField(db_column='vinN')),
                ('vin_coinbase', models.CharField(db_column='vinCoinbase')),
                ('vin_sequence', models.PositiveBigIntegerField(db_column='vinSequence')),
                ('transaction_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utxo_indexer.utxotransaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField(db_column='n')),
                ('value', models.CharField(db_column='value')),
                ('script_key_asm', models.CharField(db_column='scriptKeyAsm')),
                ('script_key_hex', models.CharField(db_column='scriptKeyHex')),
                ('script_key_req_sigs', models.CharField(blank=True, db_column='scriptKeyReqSigs', null=True)),
                ('script_key_type', models.CharField(db_column='scriptKeyType')),
                ('script_key_address', models.CharField(db_column='scriptKeyAddress', max_length=128)),
                ('transaction_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utxo_indexer.utxotransaction')),
            ],
            options={
                'unique_together': {('transaction_link', 'n')},
            },
        ),
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField(db_column='n')),
                ('value', models.CharField(db_column='value')),
                ('script_key_asm', models.CharField(db_column='scriptKeyAsm')),
                ('script_key_hex', models.CharField(db_column='scriptKeyHex')),
                ('script_key_req_sigs', models.CharField(blank=True, db_column='scriptKeyReqSigs', null=True)),
                ('script_key_type', models.CharField(db_column='scriptKeyType')),
                ('script_key_address', models.CharField(db_column='scriptKeyAddress', max_length=128)),
                ('vin_n', models.PositiveIntegerField(db_column='vinN')),
                ('vin_previous_txid', utxo_indexer.models.model_utils.HexString32ByteField(db_column='vinPreviousTxid', max_length=64)),
                ('vin_vout_index', models.PositiveIntegerField(db_column='vinVoutIndex')),
                ('vin_sequence', models.PositiveBigIntegerField(db_column='vinSequence')),
                ('vin_script_sig_asm', models.CharField(db_column='vinScriptSigAsm')),
                ('vin_script_sig_hex', models.CharField(db_column='vinScriptSigHex')),
                ('transaction_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utxo_indexer.utxotransaction')),
            ],
            options={
                'unique_together': {('transaction_link', 'vin_n')},
            },
        ),
    ]
