# Generated by Django 5.1.1 on 2024-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utxo_indexer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_version', models.CharField(max_length=256)),
                ('git_tag', models.CharField(max_length=256)),
                ('git_hash', models.CharField(max_length=40)),
                ('build_date', models.PositiveIntegerField()),
            ],
        ),
    ]
