# Generated by Django 5.1.1 on 2024-11-19 10:58

import utxo_indexer.models.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utxo_indexer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utxotransaction',
            name='payment_reference',
            field=utxo_indexer.models.model_utils.HexString32ByteField(db_column='paymentReference', max_length=64, null=True),
        ),
    ]
